image: node:latest

cache:
  paths:
    - node_modules/

deploy_production:
  stage: deploy
  only:
    - develop
  script:
    - npm install -g firebase-tools
    - npm install
    - npm run build
    - firebase use --token $FIREBASE_DEPLOY_KEY production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
