image: node:latest

cache:
  paths:
    - node_modules/

deploy_production:
  stage: deploy
  only:
    - develop
  script:
    - npm install -g firebase-tools
    - npm install
    - npm run build
    - firebase deploy --token "$FIREBASE_DEPLOY_KEY" --non-interactive
